
import javax.swing.JFrame;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author owen7900
 */
public class TankSelectMenu extends javax.swing.JDialog {

    /**
     * Creates new form TankSelectMenu
     */
    Game g = Game.game;
    public TankSelectMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBomber1 = new javax.swing.JButton();
        btnFast1 = new javax.swing.JButton();
        btnDestroyer1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBasic1 = new javax.swing.JButton();
        btnBasic2 = new javax.swing.JButton();
        btnBomber2 = new javax.swing.JButton();
        btnFast2 = new javax.swing.JButton();
        btnDestroyer2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPlay1 = new javax.swing.JButton();

        btnPlay.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBomber1.setText("Bomber Boy");
        btnBomber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBomber1ActionPerformed(evt);
            }
        });

        btnFast1.setText("Fast Tank");
        btnFast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFast1ActionPerformed(evt);
            }
        });

        btnDestroyer1.setText("Tank Destroyer");
        btnDestroyer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestroyer1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setText("Tank Select");

        btnBasic1.setText("Basic");
        btnBasic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasic1ActionPerformed(evt);
            }
        });

        btnBasic2.setText("Basic");
        btnBasic2.setPreferredSize(new java.awt.Dimension(89, 23));
        btnBasic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasic2ActionPerformed(evt);
            }
        });

        btnBomber2.setText("Bomber Boy");
        btnBomber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBomber2ActionPerformed(evt);
            }
        });

        btnFast2.setText("Fast Tank");
        btnFast2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFast2ActionPerformed(evt);
            }
        });

        btnDestroyer2.setText("Tank Destroyer");
        btnDestroyer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestroyer2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel2.setText("Player 1");

        jLabel3.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel3.setText("Player 2");

        btnPlay1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        btnPlay1.setText("Play");
        btnPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBomber2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnBomber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnBasic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnBasic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(70, 70, 70)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnFast2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDestroyer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFast1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDestroyer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(btnPlay1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBasic1)
                    .addComponent(btnFast1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBomber1)
                    .addComponent(btnDestroyer1))
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBasic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFast2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBomber2)
                    .addComponent(btnDestroyer2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBomber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBomber1ActionPerformed
        g.setTank(1, new BigBombTank(100, 100, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 1));
    }//GEN-LAST:event_btnBomber1ActionPerformed

    private void btnFast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFast1ActionPerformed
        g.setTank(1, new FastTank(100, 100, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 1));
    }//GEN-LAST:event_btnFast1ActionPerformed

    private void btnDestroyer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestroyer1ActionPerformed
        g.setTank(1, new TankDestroyer(100, 100, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 1));
    }//GEN-LAST:event_btnDestroyer1ActionPerformed

    private void btnBasic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasic1ActionPerformed
        g.setTank(1, new Tank(100, 100, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 1));
    }//GEN-LAST:event_btnBasic1ActionPerformed

    private void btnBasic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasic2ActionPerformed
        g.setTank(2, new Tank(1125, 525, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 2));
    }//GEN-LAST:event_btnBasic2ActionPerformed

    private void btnBomber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBomber2ActionPerformed
        g.setTank(2, new BigBombTank(1125, 525, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 2));
    }//GEN-LAST:event_btnBomber2ActionPerformed

    private void btnFast2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFast2ActionPerformed
        g.setTank(2, new FastTank(1125, 525, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 2));
    }//GEN-LAST:event_btnFast2ActionPerformed

    private void btnDestroyer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestroyer2ActionPerformed
        g.setTank(2, new TankDestroyer(1125, 525, Game.TANK_SIZE, Game.TANK_SIZE, ID.Tank, g, 2));
    }//GEN-LAST:event_btnDestroyer2ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        Game.game.reset();
        this.dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlay1ActionPerformed
        Game.game.reset();
        this.dispose();
    }//GEN-LAST:event_btnPlay1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TankSelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TankSelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TankSelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TankSelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TankSelectMenu dialog = new TankSelectMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBasic1;
    private javax.swing.JButton btnBasic2;
    private javax.swing.JButton btnBomber1;
    private javax.swing.JButton btnBomber2;
    private javax.swing.JButton btnDestroyer1;
    private javax.swing.JButton btnDestroyer2;
    private javax.swing.JButton btnFast1;
    private javax.swing.JButton btnFast2;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlay1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
